const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('cowork', {
  quitSaver: () => ipcRenderer.send('quit-saver'),
  close: () => ipcRenderer.send('win-close'),
  pin: (v) => ipcRenderer.send('win-pin', v),
  maximize: () => ipcRenderer.send('win-max'),
  onTasks: (cb) => ipcRenderer.on('tasks-update', (_e, payload) => cb(payload)),
  openLink: (url) => ipcRenderer.send('open-link', url),
  getVersion: () => ipcRenderer.invoke('get-app-version'),
  onWorkspace: (cb) => ipcRenderer.on('workspace-update', (_e, payload) => cb(payload)),
  openFile: (p) => ipcRenderer.send('open-file', p),
  refreshWorkspace: () => ipcRenderer.send('workspace-refresh'),
  getIssuePreview: (id) => ipcRenderer.invoke('get-issue-preview', id),
  closeIssue: (id, customField) => ipcRenderer.invoke('close-issue', id, customField),
  getRedmineConfig: () => ipcRenderer.invoke('get-redmine-config'),
  testRedmineConnection: (cfg) => ipcRenderer.invoke('test-redmine-connection', cfg),
  saveRedmineConfig: (cfg) => ipcRenderer.invoke('save-redmine-config', cfg),
  getWorkspaceDir: () => ipcRenderer.invoke('get-workspace-dir'),
  saveWorkspaceDir: (dir) => ipcRenderer.invoke('save-workspace-dir', dir),
  onMeetings: (cb) => ipcRenderer.on('meetings-update', (_e, payload) => cb(payload)),
  refreshMeetings: () => ipcRenderer.send('meetings-refresh'),
  getMeetingTranscript: (id) => ipcRenderer.invoke('get-meeting-transcript', id),
  getMeetingsDir: () => ipcRenderer.invoke('get-meetings-dir'),
  saveMeetingsDir: (dir) => ipcRenderer.invoke('save-meetings-dir', dir),
  getGlossaryState: () => ipcRenderer.invoke('get-glossary-state'),
  appendGlossary: (entries, meta) => ipcRenderer.invoke('append-glossary', entries, meta),
  saveNote: (issueId, text) => ipcRenderer.invoke('save-note', issueId, text),
  onQaTests: (cb) => ipcRenderer.on('qatest-update', (_e, payload) => cb(payload)),
  refreshQaTests: () => ipcRenderer.send('qatest-refresh'),
  getQaFailureXml: (runDir) => ipcRenderer.invoke('get-qa-failure-xml', runDir),
  getQaSources: () => ipcRenderer.invoke('get-qa-sources'),
  saveQaSources: (sources) => ipcRenderer.invoke('save-qa-sources', sources),
  getIssueFormMeta: (projectId, trackerName) => ipcRenderer.invoke('get-issue-form-meta', projectId, trackerName),
  getProjectMembers: (projectId) => ipcRenderer.invoke('get-project-members', projectId),
  draftIssueText: (rawNotes, opts) => ipcRenderer.invoke('draft-issue-text', rawNotes, opts),
  getLlmConfig: () => ipcRenderer.invoke('get-llm-config'),
  saveLlmConfig: (cfg) => ipcRenderer.invoke('save-llm-config', cfg),
  uploadIssueAttachment: (fileBuffer, filename) => ipcRenderer.invoke('upload-issue-attachment', fileBuffer, filename),
  createIssue: (form) => ipcRenderer.invoke('create-issue', form),
  // Grafana/Loki — pull-based, unlike the tabs above: the query depends on filters the
  // user is moving, so the renderer asks rather than main broadcasting. getGrafanaConfig
  // returns whether a token exists and its last four characters, never the token itself.
  getGrafanaConfig: () => ipcRenderer.invoke('get-grafana-config'),
  saveGrafanaConfig: (cfg) => ipcRenderer.invoke('save-grafana-config', cfg),
  testGrafanaConnection: (cfg) => ipcRenderer.invoke('test-grafana-connection', cfg),
  grafanaQuery: (params) => ipcRenderer.invoke('grafana-query', params),
  grafanaOverview: (params) => ipcRenderer.invoke('grafana-overview', params),
  grafanaSummary: (params) => ipcRenderer.invoke('grafana-summary', params),
  grafanaHistory: (params) => ipcRenderer.invoke('grafana-history', params),
  grafanaAppGroups: () => ipcRenderer.invoke('grafana-app-groups'),
  // meeting-notes recorder service — see main.js, the renderer never fetches it directly
  getRunnerState: () => ipcRenderer.invoke('runner-get-state'),
  onRunnerState: (cb) => ipcRenderer.on('runner-update', (_e, payload) => cb(payload)),
  startMeeting: (model, name, profile, engine) => ipcRenderer.invoke('runner-start', model, name, profile, engine),
  stopMeeting: () => ipcRenderer.invoke('runner-stop'),
  getRunnerConfig: () => ipcRenderer.invoke('get-runner-config'),
  saveRunnerConfig: (cfg) => ipcRenderer.invoke('save-runner-config', cfg)
});
